### ISSUE TITLE
Clicking in the Hierarchy on the empty space should unselect your current selection.

### ISSUE THREAD

**Issue by fillefilip8** [Hertzole/advanced-level-editor#1]
**Is your feature request related to a problem? Please describe.**
When clicking on empty space in the Hierarchy nothing happens and selection stays. Which feels like a bad user experiance.

**Describe the solution you'd like**
When clicking on empty space in the Hierarchy it should unselect whatever is currently selected.

**Additional context**
Screenshot of how it would work:
![lyl1MGgXJk](https://user-images.githubusercontent.com/5894204/106645212-56bd3780-658c-11eb-98c1-877dd1e7af1b.gif)

**Comment by Hertzole** [comment]
Added in fe4b70e.
