### ISSUE TITLE
keyboard can effect both Inputfiled and gizmos at the same time.

### ISSUE THREAD

**Issue by Bian-Sh** [Hertzole/advanced-level-editor#13]
**Bug description:**
keyboard can effect both Inputfiled and gizmos at the same time.

**To reproduce:**
1. select one  leveleditorobject ,
2. open save level modal 
3. keyin "w、e、r、t" 
4. then you can see 

**Expected behavior:**
do not effect gizmos when keyin some words.

**Screenshots:**

![FEEDBACK](https://user-images.githubusercontent.com/24520547/174535194-3dd684ff-681a-4294-bef9-7a2119d81df3.gif)

**Desktop and versions:**
 - Your OS: Windows
 - Target OS: Windows 64-bit
 - Unity version:  Unity 2020.1f1

**Additional context:**
can  alse perform drag when save level modal is display.

**Comment by Hertzole** [comment]
This has been fixed in [9f40ac5](https://github.com/Hertzole/advanced-level-editor/commit/9f40ac52c9cdf7fb160384ab6263116d98ecc3d9).

Thank you for the report!

**Comment by Bian-Sh** [comment]
i think this could be better for us  to check wether we are hover a UI when mouse click down occurred。

https://www.jianshu.com/p/212b3c1490f2

**Comment by Hertzole** [comment]
It currently does do a UI check like that along with an input field check.  
It checks if the pointer is over UI before dragging and it checks the input field before changing translation mode. I hope that satisfies your use case!
