### ISSUE TITLE
Can drag a root gameobject into a child

### ISSUE THREAD

**Issue by Bian-Sh** [Hertzole/advanced-level-editor#14]
**Bug description:**
Can drag a root gameobject into a child

**To reproduce:**
see gif below

**Expected behavior:**
nothing would happend when user drag parent into a child transform

**Screenshots:**
![FEEDBACK0](https://user-images.githubusercontent.com/24520547/174536404-293d1212-6c50-4c07-98fc-5575415fc23c.gif)

**Additional context:**
drag a gameobject to empty area should Detach from its parent,see below.
![FEEDBACK1](https://user-images.githubusercontent.com/24520547/174536855-ecd15753-d115-446b-a52e-e48a374f0ba9.gif)

**Comment by Hertzole** [comment]
Fixed in https://github.com/Hertzole/advanced-level-editor/commit/3d4dc80aacbc4ad806c48e8911ca5224acb23a01.

Thank you for the report!

**Comment by Bian-Sh** [comment]
this API may simplify your code 
https://docs.unity3d.com/ScriptReference/Transform.IsChildOf.html
