### ISSUE TITLE
ManipulationHandle is not work after change level.

### ISSUE THREAD

**Issue by Bian-Sh** [Hertzole/advanced-level-editor#16]
**Bug description:**
change one level from another ,when there has same type model ,say "cube" maybe,then after level changed the cube can not select from free space. 

**To reproduce:**
1. create a level with just a cube 、a spownpoint and one plane ，save it ，named as “one”
2. do not click "Save Level" empty our workbench.
3. then create   another cube save it as “two” 
4. after that, reload the level named "one" by  "Load Level".
5. and then , you will find that you can not select any gameobject now.

**Expected behavior:**
no matter how many times change the level. contents inside the level should be selected.
but the gameobject appeared before will not be select in the other level.

**Screenshots:**

![FEEDBACK2](https://user-images.githubusercontent.com/24520547/180974638-e1657b76-1620-468a-aaac-7bd75d6d0583.gif)

**Desktop and versions:**
 - Your OS: Windows 10
 - Target OS:  Windows 64-bit
 - Unity version: [e.g. Unity 2020.3.30f1c1]

**Comment by Hertzole** [comment]
This has been fixed in c0a5470. Thank you for your report! :)
