### ISSUE TITLE
Opening this repository with Unity 2020.3.33 results in Unity Package Manager Error

### ISSUE THREAD

**Issue by seannowotny** [Hertzole/advanced-level-editor#20]
**Bug description:**
![Unity_ALBmtKCj3B](https://user-images.githubusercontent.com/21989324/226168720-20ff2e61-ea49-4c36-9e80-c85dd0196fa1.png)

**To reproduce:**
Clone project and open with the correct Unity version 2020.3.33

**Expected behavior:**
No issues

**Desktop and versions:**
 - Your OS: Windows 10 Home 10.0.19044 Build 1944

**Comment by seannowotny** [comment]
This is fixed by adding  "com.unity.scriptablebuildpipeline": "1.19.6" to manifest.json.
Would you like me to create a Pull Request? Which branch should it target?

**Comment by Hertzole** [comment]
Hi! As far as I know, this project shouldn't use the scriptable build pipeline, but if it fixes the repo, you can create a pull request.
